DROP INDEX IF EXISTS exs_withdraw_user_id_idx;
DROP INDEX IF EXISTS exs_withdraw_update_time_idx;
DROP INDEX IF EXISTS exs_withdraw_type_idx;
DROP INDEX IF EXISTS exs_withdraw_status_idx;
DROP INDEX IF EXISTS exs_withdraw_order_id_idx;
DROP INDEX IF EXISTS exs_withdraw_asset_idx;
DROP INDEX IF EXISTS exs_user_update_time_idx;
DROP INDEX IF EXISTS exs_user_type_idx;
DROP INDEX IF EXISTS exs_user_status_idx;
DROP INDEX IF EXISTS exs_user_role_idx;
DROP INDEX IF EXISTS exs_user_phone_idx;
DROP INDEX IF EXISTS exs_user_password_idx;
DROP INDEX IF EXISTS exs_user_account_idx;
DROP INDEX IF EXISTS exs_order_user_id_idx;
DROP INDEX IF EXISTS exs_order_update_time_idx;
DROP INDEX IF EXISTS exs_order_unhedged_idx;
DROP INDEX IF EXISTS exs_order_type_idx;
DROP INDEX IF EXISTS exs_order_trigger_idx;
DROP INDEX IF EXISTS exs_order_symobl_idx;
DROP INDEX IF EXISTS exs_order_status_idx;
DROP INDEX IF EXISTS exs_order_side_idx;
DROP INDEX IF EXISTS exs_order_order_id_idx;
DROP INDEX IF EXISTS exs_order_fee_settled_idx;
DROP INDEX IF EXISTS exs_order_comm_user_type_idx;
DROP INDEX IF EXISTS exs_order_comm_status_idx;
DROP INDEX IF EXISTS exs_order_comm_create_time_idx;
DROP INDEX IF EXISTS exs_kline_symbol_idx;
DROP INDEX IF EXISTS exs_kline_start_time_idx;
DROP INDEX IF EXISTS exs_kline_interval_idx;
DROP INDEX IF EXISTS exs_holding_user_symbol_idx;
DROP INDEX IF EXISTS exs_holding_update_time_idx;
DROP INDEX IF EXISTS exs_holding_status_idx;
DROP INDEX IF EXISTS exs_holding_blowup_idx;
DROP INDEX IF EXISTS exs_holding_amount_idx;
DROP INDEX IF EXISTS exs_balance_user_area_asset_idx;
DROP INDEX IF EXISTS exs_balance_status_idx;
DROP INDEX IF EXISTS exs_balance_history_user_asset_idx;
DROP INDEX IF EXISTS exs_balance_history_status_idx;
ALTER TABLE IF EXISTS exs_user ALTER COLUMN tid DROP DEFAULT;
ALTER TABLE IF EXISTS exs_order_comm ALTER COLUMN tid DROP DEFAULT;
ALTER TABLE IF EXISTS exs_order ALTER COLUMN tid DROP DEFAULT;
ALTER TABLE IF EXISTS exs_kline ALTER COLUMN tid DROP DEFAULT;
ALTER TABLE IF EXISTS exs_holding ALTER COLUMN tid DROP DEFAULT;
ALTER TABLE IF EXISTS exs_balance_history ALTER COLUMN tid DROP DEFAULT;
ALTER TABLE IF EXISTS exs_balance ALTER COLUMN tid DROP DEFAULT;
DROP TABLE IF EXISTS exs_withdraw;
DROP SEQUENCE IF EXISTS exs_user_tid_seq;
DROP TABLE IF EXISTS exs_user;
DROP SEQUENCE IF EXISTS exs_order_tid_seq;
DROP SEQUENCE IF EXISTS exs_order_comm_tid_seq;
DROP TABLE IF EXISTS exs_order_comm;
DROP TABLE IF EXISTS exs_order;
DROP SEQUENCE IF EXISTS exs_kline_tid_seq;
DROP TABLE IF EXISTS exs_kline;
DROP SEQUENCE IF EXISTS exs_holding_tid_seq;
DROP TABLE IF EXISTS exs_holding;
DROP SEQUENCE IF EXISTS exs_balance_tid_seq;
DROP SEQUENCE IF EXISTS exs_balance_record_tid_seq;
DROP TABLE IF EXISTS exs_balance_history;
DROP TABLE IF EXISTS exs_balance;
